import type { AssetEntity, BwgEntity, CivicEntity, CivicEvent } from "./types";

/** Build an ISO timestamp for today at HH:MM (demo clock anchored on the current day). */
export function todayAt(time: string, dayOffset = 0): string {
  const [h, m] = time.split(":").map(Number);
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(h ?? 0, m ?? 0, 0, 0);
  return d.toISOString();
}

export function monthsAgoIso(months: number, day = 12): string {
  const d = new Date();
  d.setMonth(d.getMonth() - months);
  d.setDate(day);
  d.setHours(9, 0, 0, 0);
  return d.toISOString();
}

export const CURRENT_OFFICIAL = {
  id: "USR-0031",
  name: "MCD Official",
  role: "Ward Operations Officer",
  ward: "Ward 142",
};

export const WARDS = ["Ward 142", "Ward 108", "Ward 76"];

const assets: AssetEntity[] = [
  {
    id: "BIN-0037",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Residential Market",
    ward: "Ward 142",
    lat: 28.6421,
    lng: 77.2183,
    installedOn: monthsAgoIso(8, 14),
    capacityLitres: 660,
    expectedCollectionTime: "08:00",
    maintenanceRequired: true,
    historicalSimilarIncidents: 7,
    lifetime: { collections: 1240, reports: 18, repairs: 3, maintenance: 4 },
    replacedById: "BIN-0081",
    replacementReason: "Repeated damage",
    replacementDate: monthsAgoIso(1, 21),
  },
  {
    id: "BIN-0041",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Main Road",
    ward: "Ward 142",
    lat: 28.6448,
    lng: 77.2231,
    installedOn: monthsAgoIso(14, 3),
    capacityLitres: 1100,
    expectedCollectionTime: "07:30",
    maintenanceRequired: false,
    historicalSimilarIncidents: 0,
    lifetime: { collections: 980, reports: 4, repairs: 0, maintenance: 1 },
  },
  {
    id: "BIN-0052",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Sector 4 Lane",
    ward: "Ward 142",
    lat: 28.6392,
    lng: 77.2256,
    installedOn: monthsAgoIso(11, 8),
    capacityLitres: 660,
    expectedCollectionTime: "08:15",
    maintenanceRequired: false,
    historicalSimilarIncidents: 1,
    lifetime: { collections: 760, reports: 6, repairs: 1, maintenance: 1 },
  },
  {
    id: "BIN-0064",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Community Park Gate",
    ward: "Ward 142",
    lat: 28.6465,
    lng: 77.2148,
    installedOn: monthsAgoIso(19, 22),
    capacityLitres: 660,
    expectedCollectionTime: "09:00",
    maintenanceRequired: true,
    historicalSimilarIncidents: 2,
    lifetime: { collections: 1410, reports: 11, repairs: 4, maintenance: 5 },
  },
  {
    id: "BIN-0078",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Market Backlane",
    ward: "Ward 142",
    lat: 28.6408,
    lng: 77.2205,
    installedOn: monthsAgoIso(6, 5),
    capacityLitres: 1100,
    expectedCollectionTime: "08:30",
    maintenanceRequired: false,
    historicalSimilarIncidents: 3,
    lifetime: { collections: 420, reports: 9, repairs: 1, maintenance: 1 },
  },
  {
    id: "BIN-0081",
    kind: "asset",
    name: "Municipal Waste Asset",
    servicePoint: "Residential Market",
    ward: "Ward 142",
    lat: 28.6425,
    lng: 77.2191,
    installedOn: monthsAgoIso(1, 21),
    capacityLitres: 1100,
    expectedCollectionTime: "08:30",
    maintenanceRequired: false,
    historicalSimilarIncidents: 0,
    lifetime: { collections: 38, reports: 0, repairs: 0, maintenance: 0 },
    replacesId: "BIN-0037",
    replacementReason: "Repeated damage",
    replacementDate: monthsAgoIso(1, 21),
  },
];

const bwgs: BwgEntity[] = [
  {
    id: "BWG-0142",
    kind: "bwg",
    name: "Hotel Meridian Court",
    servicePoint: "Residential Market",
    ward: "Ward 142",
    lat: 28.6416,
    lng: 77.2172,
    installedOn: monthsAgoIso(22, 2),
    bwgType: "Hotel",
    registrationVerified: true,
    segregationStreams: 4,
    collectionFrequency: "Daily",
    authorisedHandler: "GreenRoute Waste Services",
    segregationIssues: 3,
    inspectionIssue: true,
  },
  {
    id: "BWG-0151",
    kind: "bwg",
    name: "Sunrise Group Housing",
    servicePoint: "Sector 4 Lane",
    ward: "Ward 142",
    lat: 28.6389,
    lng: 77.2241,
    installedOn: monthsAgoIso(30, 9),
    bwgType: "Group Housing Society",
    registrationVerified: true,
    segregationStreams: 3,
    collectionFrequency: "Daily",
    authorisedHandler: "GreenRoute Waste Services",
    segregationIssues: 0,
    inspectionIssue: false,
  },
  {
    id: "BWG-0172",
    kind: "bwg",
    name: "Capital Banquet Hall",
    servicePoint: "Main Road",
    ward: "Ward 142",
    lat: 28.6453,
    lng: 77.2217,
    installedOn: monthsAgoIso(16, 18),
    bwgType: "Banquet / Event Venue",
    registrationVerified: true,
    segregationStreams: 4,
    collectionFrequency: "Alternate days",
    authorisedHandler: "Nirmal Handlers Pvt Ltd",
    segregationIssues: 2,
    inspectionIssue: false,
  },
  {
    id: "BWG-0190",
    kind: "bwg",
    name: "Ward 142 Vegetable Mandi",
    servicePoint: "Market Backlane",
    ward: "Ward 142",
    lat: 28.6401,
    lng: 77.2196,
    installedOn: monthsAgoIso(9, 4),
    bwgType: "Wholesale Market",
    registrationVerified: false,
    segregationStreams: 4,
    collectionFrequency: "Twice daily",
    authorisedHandler: "Pending assignment",
    segregationIssues: 1,
    inspectionIssue: true,
  },
];

export const seedEntities: CivicEntity[] = [...assets, ...bwgs];

let seq = 0;
const ev = (e: Omit<CivicEvent, "id">): CivicEvent => ({ id: `EVT-${1000 + seq++}`, ...e });

export const seedEvents: CivicEvent[] = [
  // ---- Lifecycle / historical anchors
  ev({
    entityId: "BIN-0037",
    type: "installation",
    timestamp: monthsAgoIso(8, 14),
    actor: "MCD Works Division",
    title: "Asset installed",
    detail: "660 L asset commissioned at Residential Market service point",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "maintenance",
    timestamp: monthsAgoIso(4, 9),
    actor: "MNT-006",
    title: "Repair recorded",
    detail: "Lid hinge replaced after damage",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "maintenance",
    timestamp: monthsAgoIso(2, 17),
    actor: "MNT-011",
    title: "Repair recorded",
    detail: "Body dent repair, third repair on this asset",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "replacement",
    timestamp: monthsAgoIso(1, 21),
    actor: "MCD Works Division",
    title: "Replacement asset recorded",
    detail: "BIN-0081 added at the same service point — reason: repeated damage",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0081",
    type: "installation",
    timestamp: monthsAgoIso(1, 21),
    actor: "MCD Works Division",
    title: "Asset installed as replacement",
    detail: "Replaces BIN-0037 at Residential Market service point",
    location: "Residential Market, Ward 142",
  }),

  // ---- Historical recurring overflow on BIN-0037 (previous weeks)
  ev({
    entityId: "BIN-0037",
    type: "collection",
    timestamp: todayAt("08:05", -7),
    actor: "WKR-019",
    title: "Collection recorded",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "report",
    timestamp: todayAt("09:26", -7),
    actor: "Citizen (QR)",
    title: "Citizen report — Overflowing",
    issueType: "Overflowing",
    verification: "attention",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "collection",
    timestamp: todayAt("08:12", -14),
    actor: "WKR-019",
    title: "Collection recorded",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "report",
    timestamp: todayAt("09:41", -14),
    actor: "Citizen (QR)",
    title: "Citizen report — Overflowing",
    issueType: "Overflowing",
    verification: "attention",
    hasPhoto: true,
    location: "Residential Market, Ward 142",
  }),

  // ---- Today: BIN-0037 signature sequence
  ev({
    entityId: "BIN-0037",
    type: "collection",
    timestamp: todayAt("08:10"),
    actor: "WKR-019",
    title: "Collection recorded",
    detail: "Route 07 · Vehicle DL-01-AB-2042",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "report",
    timestamp: todayAt("09:18"),
    actor: "Citizen (QR)",
    title: "Citizen report — Overflowing",
    issueType: "Overflowing",
    verification: "unverified",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "report",
    timestamp: todayAt("09:32"),
    actor: "Citizen (QR)",
    title: "Citizen report — Overflowing",
    issueType: "Overflowing",
    verification: "unverified",
    hasPhoto: true,
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0037",
    type: "report",
    timestamp: todayAt("09:47"),
    actor: "Citizen (QR)",
    title: "Citizen report — Overflowing",
    issueType: "Overflowing",
    verification: "unverified",
    location: "Residential Market, Ward 142",
  }),

  // ---- Other assets today
  ev({
    entityId: "BIN-0041",
    type: "collection",
    timestamp: todayAt("07:45"),
    actor: "WKR-022",
    title: "Collection recorded",
    detail: "Route 07 · Vehicle DL-01-AB-2042",
    location: "Main Road, Ward 142",
  }),
  ev({
    entityId: "BIN-0081",
    type: "collection",
    timestamp: todayAt("08:20"),
    actor: "WKR-019",
    title: "Collection recorded",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BIN-0064",
    type: "maintenance",
    timestamp: todayAt("10:05"),
    actor: "MNT-011",
    title: "Maintenance inspection",
    detail: "Fourth repair request raised for this asset",
    location: "Community Park Gate, Ward 142",
  }),
  ev({
    entityId: "BIN-0078",
    type: "report",
    timestamp: todayAt("10:22"),
    actor: "Citizen (QR)",
    title: "Citizen report — Improper dumping",
    issueType: "Improper dumping",
    verification: "unverified",
    location: "Market Backlane, Ward 142",
  }),
  ev({
    entityId: "BIN-0052",
    type: "report",
    timestamp: todayAt("11:02"),
    actor: "Citizen (QR)",
    title: "Citizen report — Waste not collected",
    issueType: "Waste not collected",
    verification: "unverified",
    location: "Sector 4 Lane, Ward 142",
  }),

  // ---- BWG-0142 compliance chain
  ev({
    entityId: "BWG-0142",
    type: "compliance",
    timestamp: monthsAgoIso(3, 11),
    actor: "MCD Inspection Cell",
    title: "Segregation issue observed",
    detail: "Wet and dry streams mixed at handover",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "compliance",
    timestamp: monthsAgoIso(1, 8),
    actor: "MCD Inspection Cell",
    title: "Segregation issue observed",
    detail: "Second recorded instance within the quarter",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "collection",
    timestamp: todayAt("07:20", -1),
    actor: "GreenRoute Waste Services",
    title: "Collection recorded",
    detail: "Authorised handler pickup",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "report",
    timestamp: todayAt("09:55", -1),
    actor: "Citizen (QR)",
    title: "Citizen report — Mixed waste observed",
    issueType: "Mixed waste observed",
    verification: "unverified",
    hasPhoto: true,
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "collection",
    timestamp: todayAt("07:15"),
    actor: "GreenRoute Waste Services",
    title: "Collection recorded",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "inspection",
    timestamp: todayAt("11:30"),
    actor: "INS-004",
    title: "Inspection — segregation issue observed",
    detail: "4-stream requirement not met at time of inspection",
    location: "Residential Market, Ward 142",
  }),
  ev({
    entityId: "BWG-0142",
    type: "report",
    timestamp: todayAt("11:52"),
    actor: "Citizen (QR)",
    title: "Citizen report — Mixed waste observed",
    issueType: "Mixed waste observed",
    verification: "unverified",
    location: "Residential Market, Ward 142",
  }),

  // ---- Other BWGs
  ev({
    entityId: "BWG-0151",
    type: "collection",
    timestamp: todayAt("07:05"),
    actor: "GreenRoute Waste Services",
    title: "Collection recorded",
    location: "Sector 4 Lane, Ward 142",
  }),
  ev({
    entityId: "BWG-0172",
    type: "compliance",
    timestamp: todayAt("12:40", -2),
    actor: "MCD Inspection Cell",
    title: "Segregation issue observed",
    detail: "Event-day waste handed over unsegregated",
    location: "Main Road, Ward 142",
  }),
  ev({
    entityId: "BWG-0172",
    type: "report",
    timestamp: todayAt("13:10", -1),
    actor: "Citizen (QR)",
    title: "Citizen report — Mixed waste observed",
    issueType: "Mixed waste observed",
    verification: "unverified",
    location: "Main Road, Ward 142",
  }),
  ev({
    entityId: "BWG-0190",
    type: "inspection",
    timestamp: todayAt("09:10"),
    actor: "INS-007",
    title: "Inspection — registration pending",
    detail: "Registration and authorised handler not on record",
    location: "Market Backlane, Ward 142",
  }),
];

/** Headline demo figures quoted in the brief (illustrative prototype data). */
export const DEMO_TOTALS = {
  assets: 38,
  bwgs: 17,
  collections: 124,
  reports: 31,
};
