/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsEntityIdRouteImport } from './routes/assets.$entityId'
import { Route as BwgsIndexRouteImport } from './routes/bwgs.index'
import { Route as BwgsEntityIdRouteImport } from './routes/bwgs.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsEntityIdRoute = AssetsEntityIdRouteImport.update({
  id: '/assets/$entityId',
  path: '/assets/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const BwgsIndexRoute = BwgsIndexRouteImport.update({
  id: '/bwgs/',
  path: '/bwgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BwgsEntityIdRoute = BwgsEntityIdRouteImport.update({
  id: '/bwgs/$entityId',
  path: '/bwgs/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$entityId': typeof AssetsEntityIdRoute
  '/bwgs/$entityId': typeof BwgsEntityIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/bwgs/': typeof BwgsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$entityId': typeof AssetsEntityIdRoute
  '/bwgs/$entityId': typeof BwgsEntityIdRoute
  '/assets': typeof AssetsIndexRoute
  '/bwgs': typeof BwgsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$entityId': typeof AssetsEntityIdRoute
  '/bwgs/$entityId': typeof BwgsEntityIdRoute
  '/assets/': typeof AssetsIndexRoute
  '/bwgs/': typeof BwgsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/assets/$entityId' | '/bwgs/$entityId' | '/assets/' | '/bwgs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assets/$entityId' | '/bwgs/$entityId' | '/assets' | '/bwgs'
  id:
    | '__root__'
    | '/'
    | '/assets/$entityId'
    | '/bwgs/$entityId'
    | '/assets/'
    | '/bwgs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsEntityIdRoute: typeof AssetsEntityIdRoute
  BwgsEntityIdRoute: typeof BwgsEntityIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  BwgsIndexRoute: typeof BwgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$entityId': {
      id: '/assets/$entityId'
      path: '/assets/$entityId'
      fullPath: '/assets/$entityId'
      preLoaderRoute: typeof AssetsEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bwgs/': {
      id: '/bwgs/'
      path: '/bwgs'
      fullPath: '/bwgs/'
      preLoaderRoute: typeof BwgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bwgs/$entityId': {
      id: '/bwgs/$entityId'
      path: '/bwgs/$entityId'
      fullPath: '/bwgs/$entityId'
      preLoaderRoute: typeof BwgsEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsEntityIdRoute: AssetsEntityIdRoute,
  BwgsEntityIdRoute: BwgsEntityIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  BwgsIndexRoute: BwgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
